### PR TITLE
Add option to filter when tags listed in tags array

### PR DESCRIPTION
**Pull request by andrzejwp**
This PR provides option for the case when tags are listed as per OpenAPI spec, inside `tags:[]` property.

For example this is how a path, tagged with `GraphQL` could be filtered out:

```
openapi-filter --tags GraphQL --checkArray -i -- open-api-schema.json 
{
  "paths": {
    "/api/graphql": {
      "post": {
        "operationId": "graphQL",
        "description": "Endpoint for GraphQL Queries for Headless Types",
        "tags": [
          "GraphQL"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "query": {
                    "type": "string",
                    "format": "text",
                    "description": "Graph QL query, for example: query{productsList{id,name}}"
                  }
                },
                "required": [
                  "query"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/graphql/schema": {
      "get": {
        "operationId": "graphQLSchema",
        "description": "Get current descripion of GraphQL Schema",
        "tags": [
          "GraphQL"
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by Hobart2967** [comment]
+1

**Comment by martinlabuschin** [comment]
+1

**Comment by MikeRalphson** [comment]
Thanks, this has been released as part of `v2.0.0` (renamed to `--checkTags`).

**Comment by andrzejwp** [comment]
Awesome, thank you!

**Pull request merged**
