### PR TITLE
Add support for filtering based on string field values for the --flags option

### PR DESCRIPTION
**Pull request by aregier**
The default behavior assumes the fields identified by the `--flags` option are boolean data types and that the filter will look for true. This extends the functionality to be able to look for strings (e.g. "--flagValues private hidden hide")

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Just to clarify, the current code does not (only) look for boolean type extensions with value `true`, it looks for "truthy" expressions, i.e. boolean `true`, non-empty strings, or arrays or objects.

Does this affect the need for this PR? I think your confusion arises from a reading of the code not the documentation, but I'd be open to improvements to the README also.

**Comment by aregier** [comment]
Thanks for the response. Yes, truthy expressions seem to work very well for most data types, but not being able to filter more distinctly on string values is painful. Consider the set of possible values ["public", "private", "internal"]. It would be nice to be able to use the filter to exclude matches where the flag key value is present and the values match either "private" or "internal" using "--flagValues private internal".

If it is helpful, this change could be modified to retain the truthy behavior for all data types other than `string`. I'm not sure if anyone is depending on the current behavior for strings -- It looked like a data type that was not really accounted for in the design.

**Comment by MikeRalphson** [comment]
No, the current behaviour of string extensions should definitely remain if `--flagValues` is not specified. E.g. `x-internal: "For testing only"`.

**Comment by aregier** [comment]
@MikeRalphson Thanks again. I pushed a commit that should ensure the current behavior is preserved for all data types unless the `--flagValues` option is actively used.

**Comment by MikeRalphson** [comment]
Ok, let me add any missing tests and I'll take another look. Thanks.

**Comment by aregier** [comment]
@MikeRalphson I just saw this. My apologies. I can easily add a covering mocha test for the new functionality as well.

**Comment by aregier** [comment]
A basic test added for the new functionality covering 2 of 3 string values being filtered out. I *think* the existing tests provide some decent coverage for existing behavior for regression test purposes, but let me know if they need to be augmented.

I had imagined this feature for string types, but we could consider it for other data types as well

**Comment by aregier** [comment]
@MikeRalphson Any update on this one?

**Comment by MikeRalphson** [comment]
Thanks for the prompt!

**Comment by MikeRalphson** [comment]
Published as part of `v3.1.0`

**Pull request merged**
