### PR TITLE
Use maxAliasCount = -1 in yaml.parse options.

### LINKED ISSUE #22: ReferenceError: Excessive alias count indicates a resource exhaustion attack
When YAML API specifications that contain many aliases openapi-filter may fail. This is caused by a more strict `maxAliasCount` in YAML

https://github.com/eemeli/yaml/blob/440aadcd703c76f8920f75bde9d0ea522eb3a08a/src/index.js#L14

Since `openapi-filter` is a command line tool I think it's safe to turn off this check by setting `maxAliasCount=-1` in yaml `parse` options. I will submit a PR for this later today.

### PR DESCRIPTION
**Pull request by thovden**
APIs that use YAML aliases may fail due to a Denial-of-service security check in `yaml`. 

For `openapi-filter` this check is not relevant, and it can be turned off using the `maxAliasCount` option to `yaml.parse`. 

This PR sets `maxAliasCount` to `-1`, turning off the check. I've also included an example YAML file that triggers the problem when running default settings. 

Closes #22

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks, but why do you say

> For openapi-filter this check is not relevant

Your example OpenAPI file does not seem to be valid as it uses features of YAML above and beyond those compatible with JSON. YAML merge keys are a YAML 1.1 feature and OpenAPI (3.x at least) mandates YAML 1.2. Can your OpenAPI definition not be specified simply using `$ref`s?

**Comment by thovden** [comment]
@MikeRalphson That's news to me, and I'm not a YAML expert in any sense of the word. So if the YAML provided in the example is not valid feel free to reject this PR. I do, however, use it with AWS API Gateway after transforming it to JSON.

**Comment by MikeRalphson** [comment]
I think I would feel more comfortable with adding a new `openapi-filter` option to control directly the `yaml` `maxAliasCount` option (and probably have it default to 100 as per `yaml`).

**Comment by thovden** [comment]
That seems like a good solution!

**Comment by MikeRalphson** [comment]
Just taking the new test file and will add the new option. Thanks again.

**Pull request merged**
