### PR TITLE
add npm global support

### LINKED ISSUE #4: Can't run module globally
Installing with `npm install -g openapi-filter` or running with `npx openapi-filter` results in `command not found: openapi-filter` error.

### PR DESCRIPTION
**Pull request by wshirey**
Fixes #4

### CODE REVIEW

**Comment by wshirey** [comment]
I published another npm repo named `openapi-filter-wshirey` so you can test. Following commands should work

- `npm install -g openapi-filter-wshirey && openapi-filter-wshirey`
- `npx openapi-filter-wshirey`

I'll delete it if you merge this.

**Comment by MikeRalphson** [comment]
Thanks, this is really helpful.

**Comment by MikeRalphson** [comment]
Published as v1.2.2

**Comment by wshirey** [comment]
> Thanks, this is really helpful.

No, thank *you* for your library!

**Comment by MikeRalphson** [comment]
I've also made similar fixes to the related project `openapi-extract` - thanks for pointing out, it's something I always forget when publishing!

**Pull request merged**
