### PR TITLE
Introduce new option to keep nested references when filtering with --inverse

### PR DESCRIPTION
**Pull request by jdworschak**
This introduces a new option `--keepReferences` to check for and keep nested references when filtering with `--inverse`. It also deprecates `--valid` in favor of the new option since `--valid` only works in some cases, see #29.

I chose to go with a deprecation because this changes the current behavior for people using `--valid`. The asyncapi test would fail for example when using the new approach vs. the one-shot ref check implemented with `--valid`. In my opinion it produces a more correct result than before, but might of course change documentation for some peoply in existing documentation pipelines. I'm also by no means as expert on the different documentation formats supported by this project, so I might have missed something.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks, will check out and test!

**Comment by Oupsla** [comment]
Got the issue that you have linked (missing references) and test your branch with keepReferences flag, works pretty well on my schema 👍

**Comment by MikeRalphson** [comment]
Thanks again @jdworschak and thanks for being cautious with implementing a potentially breaking change. I've also added a test for circular references locally, and your change works for that case too, excellent stuff.

That said, I think I would like to keep `--valid` and avoid a new option `--keepReferences` which does *more* than just keeping references, so we would not change the contract of the program, even though we are changing the result. Though this is really a bugfix, I appreciate your point about people with this program embedded in a pipeline.

I think my preferred option would be to simply bump the major version and keep the options as they are. Are you interested in progressing the PR along those lines, or should I merge and re-work?

**Comment by jdworschak** [comment]
Hi @MikeRalphson, appreciate the feedback! Sorry for getting back on this so late. I've been a bit pressed for time lately.

I removed the new option and reworked my changes into the existing`--valid`. I also fixed the existing `asyncapi` test since it didn't previously include some of the refs that should have been preserved in its output.

I think some more tests should probably be added for other documentation formats as well but as I mentioned I don't really  have a strong background with those so I wouldn't feel comfortable doing that. Feel free to merge and re-work or just bump the version however you think is best.

**Comment by MikeRalphson** [comment]
Thank you so much for finding the time to rework this, it is very much appreciated.

**Pull request merged**
